# Name of your web site
# サイトの名前
siteName: blog-maker

# Use your own domain
# 独自ドメインを使用する場合は true にする
ownDomain: false

# Do not display the page title on the top page
# トップページでページタイトルを表示しない
showTitleOnlyInArticles: true

# Allow future dates
# 未来の日付を許可する
future: true
