# Name of your web site
# サイトの名前
siteName: blog-maker

# Use your own domain
# 独自ドメインを使用する場合は true にする
ownDomain: false

# Specify URL not to display title & back2top
# ページタイトルとback2topを表示しないURL
disableShowingTitle: ["/"]

# Allow future dates
# 未来の日付を許可する
future: true
